title: Austin Bond, GRC Portfolio
description: ISO 27001:2022 ISMS Implementation — German Market Focus
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
search_enabled: true
aux_links:
  "GitHub Repo": https://github.com/austinbondgrc/grc-portfolio
nav_sort: case_sensitive  
